apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    # add an annotation indicating the issuer to use.
    cert-manager.io/cluster-issuer: letsencrypt
    route.openshift.io/termination: "reencrypt"
    route.openshift.io/destination-ca-certificate-secret: "{{ certNames.internalCA }}"
  labels:
    ingress: letsencrypt
    mas.ibm.com/instanceId: "{{ instanceId }}"
    app.kubernetes.io/instance: "{{ instanceId }}"
    app.kubernetes.io/managed-by: "{{ operatorName }}"
    app.kubernetes.io/name: ibm-mas
  name: "{{ instanceId }}-auth"
  namespace: "{{ coreNamespace }}"
spec:
  rules:
  - host: "auth.{{ domain }}"
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: coreidp
            port:
              name: coreidp
  tls:
  - hosts:
    - "{{ domain }}"
    - "auth.{{ domain }}"
    secretName:  "letsencrypt-{{ instanceId }}-auth"
