apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: mas-core-letsencrypt
    files:
      - update-ansible.sh
      - coreidp-routes.yml=mas-entitymgr-coreidp/roles/coreidp/tasks/routes.yml
      - coreidp-ingress.yml=mas-entitymgr-coreidp/roles/coreidp/templates/coreidp/ingress.yml
      - coreidp-login-ingress.yml=mas-entitymgr-coreidp/roles/coreidp/templates/coreidp-login/ingress.yml
      - suite-routes.yml=mas-entitymgr-suite/roles/suite/tasks/networking/routes.yml
      - suite-ingress.yml.j2=mas-entitymgr-suite/roles/suite/templates/networking/ingress.yml.j2
      - suite-admin.yml=mas-entitymgr-suite/roles/suite/templates/networking/ingress/admin.yml
      - suite-api.yml=mas-entitymgr-suite/roles/suite/templates/networking/ingress/api.yml
      - suite-home.yml=mas-entitymgr-suite/roles/suite/templates/networking/ingress/home.yml
      - ws-main.yml=mas-entitymgr-ws/roles/workspace/tasks/main.yml
      - ws-ingress.yml=mas-entitymgr-ws/roles/workspace/templates/routes/ingress.yml

resources:
  - job.yaml
  - cronjob.yaml
